### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by tom-doerr** [jina-ai/dalle-flow#12]
Generating images currently doesn't seem to work.
When running the cell 
```
%%time

from docarray import Document

da = Document(text=prompt).post(server_url, parameters={'num_images': 8}).matches

da.plot_image_sprites(fig_size=(10,10), show_index=True)
```

I get the following error:
```
ERROR  GRPCClient@60 gRPC error: StatusCode.UNAVAILABLE failed to connect [05/12/22 22:12:59]
       to all addresses                                                                      
       the ongoing request is terminated as the server is not available                      
       or closed already                                                                     
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/jina/helper.py", line 1311, in run
    self.result = asyncio.run(func(*args, **kwargs))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/jina/clients/mixin.py", line 147, in _get_results
    async for resp in c._get_results(*args, **kwargs):
  File "/usr/local/lib/python3.7/dist-packages/jina/clients/base/grpc.py", line 128, in _get_results
    raise e
  File "/usr/local/lib/python3.7/dist-packages/jina/clients/base/grpc.py", line 95, in _get_results
    raise rpc_ex
  File "/usr/local/lib/python3.7/dist-packages/jina/clients/base/grpc.py", line 65, in _get_results
    compression.lower(), grpc.Compression.NoCompression
  File "/usr/local/lib/python3.7/dist-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
    await self._raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/grpc/aio/_call.py", line 237, in _raise_for_status
    self._cython_call.status())
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1652393579.737216803","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3217,"referenced_errors":[{"created":"@1652393579.737215929","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":165,"grpc_status":14}]}"
>

╭──────────────────────────── Traceback (most recent call last) ────────────────────────────╮
│ /usr/local/lib/python3.7/dist-packages/jina/helper.py:1326 in run_async                   │
│                                                                                           │
│   1323 │   │   │   thread.start()                                                         │
│   1324 │   │   │   thread.join()                                                          │
│   1325 │   │   │   try:                                                                   │
│ ❱ 1326 │   │   │   │   return thread.result                                               │
│   1327 │   │   │   except AttributeError:                                                 │
│   1328 │   │   │   │   from jina.excepts import BadClient                                 │
│   1329                                                                                    │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: '_RunThread' object has no attribute 'result'

During handling of the above exception, another exception occurred:

╭──────────────────────────── Traceback (most recent call last) ────────────────────────────╮
│ /usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882 in run_code  │
│                                                                                           │
│   2879 │   │   │   try:                                                                   │
│   2880 │   │   │   │   self.hooks.pre_run_code_hook()                                     │
│   2881 │   │   │   │   #rprint('Running code', repr(code_obj)) # dbg                      │
│ ❱ 2882 │   │   │   │   exec(code_obj, self.user_global_ns, self.user_ns)                  │
│   2883 │   │   │   finally:                                                               │
│   2884 │   │   │   │   # Reset our crash handler in place                                 │
│   2885 │   │   │   │   sys.excepthook = old_excepthook                                    │
│ <ipython-input-4-c8bf11265368>:1 in <module>                                              │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2117 in           │
│ run_cell_magic                                                                            │
│                                                                                           │
│   2114 │   │   │   stack_depth = 2                                                        │
│   2115 │   │   │   magic_arg_s = self.var_expand(line, stack_depth)                       │
│   2116 │   │   │   with self.builtin_trap:                                                │
│ ❱ 2117 │   │   │   │   result = fn(magic_arg_s, cell)                                     │
│   2118 │   │   │   return result                                                          │
│   2119 │                                                                                  │
│   2120 │   def find_line_magic(self, magic_name):                                         │
│ <decorator-gen-53>:2 in time                                                              │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/IPython/core/magic.py:188 in <lambda>              │
│                                                                                           │
│   185 │   # This is a closure to capture the magic_kind.  We could also use a class,      │
│   186 │   # but it's overkill for just that one bit of state.                             │
│   187 │   def magic_deco(arg):                                                            │
│ ❱ 188 │   │   call = lambda f, *a, **k: f(*a, **k)                                        │
│   189 │   │                                                                               │
│   190 │   │   if callable(arg):                                                           │
│   191 │   │   │   # "Naked" decorator call (just @foo, no args)                           │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/IPython/core/magics/execution.py:1193 in time      │
│                                                                                           │
│   1190 │   │   │   end = clock2()                                                         │
│   1191 │   │   else:                                                                      │
│   1192 │   │   │   st = clock2()                                                          │
│ ❱ 1193 │   │   │   exec(code, glob, local_ns)                                             │
│   1194 │   │   │   end = clock2()                                                         │
│   1195 │   │   │   out = None                                                             │
│   1196 │   │   wall_end = wtime()                                                         │
│ <timed exec>:4 in <module>                                                                │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/docarray/document/mixins/sugar.py:92 in post       │
│                                                                                           │
│   89 │   │   from ... import DocumentArray                                                │
│   90 │   │                                                                                │
│   91 │   │   _tmp = DocumentArray(self)                                                   │
│ ❱ 92 │   │   return _tmp.post(*args, **kwargs)[0]                                         │
│   93                                                                                      │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/docarray/array/mixins/post.py:85 in post           │
│                                                                                           │
│   82 │   │   │   │   show_progress=show_progress,                                         │
│   83 │   │   │   │   request_size=batch_size,                                             │
│   84 │   │   │   │   parameters=parameters,                                               │
│ ❱ 85 │   │   │   │   **kwargs,                                                            │
│   86 │   │   │   )                                                                        │
│   87 │   │   else:                                                                        │
│   88 │   │   │   raise ValueError(f'unsupported scheme: {r.scheme}')                      │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/jina/clients/mixin.py:166 in post                  │
│                                                                                           │
│   163 │   │   │   target_executor=target_executor,                                        │
│   164 │   │   │   parameters=parameters,                                                  │
│   165 │   │   │   request_size=request_size,                                              │
│ ❱ 166 │   │   │   **kwargs,                                                               │
│   167 │   │   )                                                                           │
│   168 │                                                                                   │
│   169 │   # ONLY CRUD, for other request please use `.post`                               │
│                                                                                           │
│ /usr/local/lib/python3.7/dist-packages/jina/helper.py:1331 in run_async                   │
│                                                                                           │
│   1328 │   │   │   │   from jina.excepts import BadClient                                 │
│   1329 │   │   │   │                                                                      │
│   1330 │   │   │   │   raise BadClient(                                                   │
│ ❱ 1331 │   │   │   │   │   'something wrong when running the eventloop, result can not be │
│   1332 │   │   │   │   )                                                                  │
│   1333 │   │   else:                                                                      │
│   1334                                                                                    │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
BadClient: something wrong when running the eventloop, result can not be retrieved
```

**Comment by h0merg0mez** [comment]
Same issue for me in the Colab

**Comment by iperezr** [comment]
I can confirm the same issue in Colab

**Comment by hanxiao** [comment]
Thanks for the report, fixing it now.

**Comment by hanxiao** [comment]
Solved, please reopen the notebook or update the server address

**Comment by fancsiko** [comment]
What should I do if I still have the same error? I opened the notebook just recently. What is the server address should be updated to?

**Comment by dmd** [comment]
I'm getting this as well.
