### ISSUE TITLE
ImportError: cannot import name 'MofNCompleteColumn' from 'rich.progress'

### ISSUE THREAD

**Issue by 6174** [jina-ai/dalle-flow#41]
Have this issue after run jina flow 

My device is Mac Pro M1 

```
➜  dalle-flow git:(main) jina flow --uses flow.yml
Traceback (most recent call last):
  File "/usr/local/bin/jina", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/jina_cli/__init__.py", line 141, in main
    args = _get_run_args()
  File "/usr/local/lib/python3.9/site-packages/jina_cli/__init__.py", line 8, in _get_run_args
    from jina.helper import get_rich_console
  File "/usr/local/lib/python3.9/site-packages/jina/__init__.py", line 200, in <module>
    from jina.orchestrate.flow.asyncio import AsyncFlow
  File "/usr/local/lib/python3.9/site-packages/jina/orchestrate/flow/asyncio.py", line 2, in <module>
    from jina.orchestrate.flow.base import Flow
  File "/usr/local/lib/python3.9/site-packages/jina/orchestrate/flow/base.py", line 29, in <module>
    from rich.progress import (
ImportError: cannot import name 'MofNCompleteColumn' from 'rich.progress' (/usr/local/lib/python3.9/site-packages/rich/progress.py)
```

**Comment by hanxiao** [comment]
`pip install -U rich`
