### ISSUE TITLE
OperationalError: database is locked in MyStore executor

### ISSUE THREAD

**Issue by mistamun** [jina-ai/dalle-flow#45]
I'm getting this error when launching the server both in Docker or natively.

the dalle-flow.db gets created with 777 but then this database is locked error occurs and no tables are ever initialised, the file remains empty.

I made no changes to the executor or the yml file and DocumentArray initialisation seems correct...

```python
from jina import Executor, requests, DocumentArray
from jina.logging.predefined import default_logger


class MyStore(Executor):

    def __init__(self, store_path: str, **kwargs):
        super().__init__(**kwargs)
        self.storage = DocumentArray(storage='sqlite', config={'connection': store_path, 'table_name': f'dallemega'})

```

**Comment by JoanFM** [comment]
Hey @mistamun ,

may you please add details about the exact error you are seeing?

**Comment by hanxiao** [comment]
`OperationalError: database is locked` happened when multiple replicas trying to write at the same time, are you using one or multiple replicas for `MyStore` executors?

**Comment by mistamun** [comment]
`flow_test.yml`

```
jtype: Flow
with:
  protocol: grpc
  port: 51005
  env:
    JINA_LOG_LEVEL: debug
executors:
  - name: store
    uses: MyStore
    py_modules:
      - executors/store/executor.py
    uses_with:
      store_path: dalle-flow.db
```

`executor.py` no change from main branch
```
from jina import Executor, requests, DocumentArray
from jina.logging.predefined import default_logger


class MyStore(Executor):

    def __init__(self, store_path: str, **kwargs):
        super().__init__(**kwargs)
        self.storage = DocumentArray(storage='sqlite', config={'connection': store_path, 'table_name': f'dallemega'})

    @requests(on='/upscale')
    def store(self, docs: DocumentArray, **kwargs):
        docs[...].blobs = None  # remove all blobs from anywhere to save space
        docs[...].embeddings = None
        for d in docs.find({'tags__upscaled': {'$exists': True}}):
            if d.id not in self.storage:
                self.storage.append(d)
                default_logger.info(f'total: {len(self.storage)}')
```

traceback:

```
user@dalle:~/dalle/dalle-flow$ jina flow --uses flow_test.yml

/anaconda/envs/tunfas/bin/jina flow --uses         
flow_test.yml                                      
╭──────────────┬──────────────────────────────────╮
│     Argument │ Value                            │
├──────────────┼──────────────────────────────────┤
│          cli │ flow                             │
│          env │ None                             │
│      inspect │ COLLECT                          │
│   log-config │ default                          │
│         name │ None                             │
│        quiet │ False                            │
│  quiet-error │ False                            │
│         uses │ flow_test.yml                    │
│    workspace │ None                             │
│ workspace-id │ 083e0b0aa2234f94b96122341ebf4d3c │
╰──────────────┴──────────────────────────────────╯
⠋  Waiting ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/0 -:--:--DEBUG  gateway/rep-0@18162 adding connection for deployment store/heads/0 to grpc://0.0.0.0:57701                                                                                                                                                                                           [06/22/22 11:15:00]
⠙ Waiting store gateway ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/2 0:00:00DEBUG  gateway/rep-0@18162 start server bound to 0.0.0.0:51005                                                                                                                                                                                                                                                 
DEBUG  gateway/rep-0@18022 ready and listening                                                                                                                                                                                                                                              [06/22/22 11:15:00]
⠇ Waiting store ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 1/2 0:00:05CRITI… store/rep-0@18161 can not load the executor from MyStore                                                                                                                                                                                                                             [06/22/22 11:15:05]
⠼ Waiting store ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 1/2 0:00:05ERROR  store/rep-0@18161 OperationalError('database is locked') during <class 'jina.serve.runtimes.worker.WorkerRuntime'> initialization                                                                                                                                                    [06/22/22 11:15:05]
        add "--quiet-error" to suppress the exception details                                                                                                                                                                                                                                                  
       ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/jina/orchestrate/pods/__init__.py:74 in run                                                                                                                                                                                    │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    71 │                                                                                                                                                                                                                                                                          │                    
       │    72 │   try:                                                                                                                                                                                                                                                                   │                    
       │    73 │   │   _set_envs()                                                                                                                                                                                                                                                        │                    
       │ ❱  74 │   │   runtime = runtime_cls(                                                                                                                                                                                                                                             │                    
       │    75 │   │   │   args=args,                                                                                                                                                                                                                                                     │                    
       │    76 │   │   )                                                                                                                                                                                                                                                                  │                    
       │    77 │   except Exception as ex:                                                                                                                                                                                                                                                │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/jina/serve/runtimes/worker/__init__.py:31 in __init__                                                                                                                                                                          │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    28 │   │   :param kwargs: keyword args                                                                                                                                                                                                                                        │                    
       │    29 │   │   """                                                                                                                                                                                                                                                                │                    
       │    30 │   │   self._health_servicer = health.HealthServicer(experimental_non_blocking=True)                                                                                                                                                                                      │                    
       │ ❱  31 │   │   super().__init__(args, **kwargs)                                                                                                                                                                                                                                   │                    
       │    32 │                                                                                                                                                                                                                                                                          │                    
       │    33 │   async def async_setup(self):                                                                                                                                                                                                                                           │                    
       │    34 │   │   """                                                                                                                                                                                                                                                                │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/jina/serve/runtimes/asyncio.py:66 in __init__                                                                                                                                                                                  │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    63 │   │   │   )                                                                                                                                                                                                                                                              │                    
       │    64 │   │                                                                                                                                                                                                                                                                      │                    
       │    65 │   │   self._setup_monitoring()                                                                                                                                                                                                                                           │                    
       │ ❱  66 │   │   self._loop.run_until_complete(self.async_setup())                                                                                                                                                                                                                  │                    
       │    67 │                                                                                                                                                                                                                                                                          │                    
       │    68 │   def run_forever(self):                                                                                                                                                                                                                                                 │                    
       │    69 │   │   """                                                                                                                                                                                                                                                                │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/asyncio/base_events.py:616 in run_until_complete                                                                                                                                                                                             │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    613 │   │   if not future.done():                                                                                                                                                                                                                                             │                    
       │    614 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')                                                                                                                                                                                             │                    
       │    615 │   │                                                                                                                                                                                                                                                                     │                    
       │ ❱  616 │   │   return future.result()                                                                                                                                                                                                                                            │                    
       │    617 │                                                                                                                                                                                                                                                                         │                    
       │    618 │   def stop(self):                                                                                                                                                                                                                                                       │                    
       │    619 │   │   """Stop running the event loop.                                                                                                                                                                                                                                   │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/jina/serve/runtimes/worker/__init__.py:58 in async_setup                                                                                                                                                                       │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    55 │   │   else:                                                                                                                                                                                                                                                              │                    
       │    56 │   │   │   self._summary_time = contextlib.nullcontext()                                                                                                                                                                                                                  │                    
       │    57 │   │                                                                                                                                                                                                                                                                      │                    
       │ ❱  58 │   │   await self._async_setup_grpc_server()                                                                                                                                                                                                                              │                    
       │    59 │                                                                                                                                                                                                                                                                          │                    
       │    60 │   async def _async_setup_grpc_server(self):                                                                                                                                                                                                                              │                    
       │    61 │   │   """                                                                                                                                                                                                                                                                │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/jina/serve/runtimes/worker/__init__.py:68 in _async_setup_grpc_server                                                                                                                                                          │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    65 │   │   # Keep this initialization order                                                                                                                                                                                                                                   │                    
       │    66 │   │   # otherwise readiness check is not valid                                                                                                                                                                                                                           │                    
       │    67 │   │   # The DataRequestHandler needs to be started BEFORE the grpc server                                                                                                                                                                                                │                    
       │ ❱  68 │   │   self._data_request_handler = DataRequestHandler(                                                                                                                                                                                                                   │                    
       │    69 │   │   │   self.args, self.logger, self.metrics_registry                                                                                                                                                                                                                  │                    
       │    70 │   │   )                                                                                                                                                                                                                                                                  │                    
       │    71                                                                                                                                                                                                                                                                            │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/jina/serve/runtimes/request_handlers/data_request_handler.py:41 in __init__                                                                                                                                                    │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    38 │   │   self.args.parallel = self.args.shards                                                                                                                                                                                                                              │                    
       │    39 │   │   self.logger = logger                                                                                                                                                                                                                                               │                    
       │    40 │   │   self._is_closed = False                                                                                                                                                                                                                                            │                    
       │ ❱  41 │   │   self._load_executor(metrics_registry)                                                                                                                                                                                                                              │                    
       │    42 │   │   self._init_monitoring(metrics_registry)                                                                                                                                                                                                                            │                    
       │    43 │                                                                                                                                                                                                                                                                          │                    
       │    44 │   def _init_monitoring(self, metrics_registry: Optional['CollectorRegistry'] = None):                                                                                                                                                                                    │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/jina/serve/runtimes/request_handlers/data_request_handler.py:79 in _load_executor                                                                                                                                              │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    76 │   │   :param metrics_registry: Optional prometheus metrics registry that will be                                                                                                                                                                                         │                    
       │       passed to the executor so that it can expose metrics                                                                                                                                                                                                                       │                    
       │    77 │   │   """                                                                                                                                                                                                                                                                │                    
       │    78 │   │   try:                                                                                                                                                                                                                                                               │                    
       │ ❱  79 │   │   │   self._executor: BaseExecutor = BaseExecutor.load_config(                                                                                                                                                                                                       │                    
       │    80 │   │   │   │   self.args.uses,                                                                                                                                                                                                                                            │                    
       │    81 │   │   │   │   uses_with=self.args.uses_with,                                                                                                                                                                                                                             │                    
       │    82 │   │   │   │   uses_metas=self.args.uses_metas,                                                                                                                                                                                                                           │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/jina/jaml/__init__.py:760 in load_config                                                                                                                                                                                       │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │   757 │   │   │   │   # revert yaml's tag and load again, this time with substitution                                                                                                                                                                                            │                    
       │   758 │   │   │   │   tag_yml = JAML.unescape(JAML.dump(no_tag_yml))                                                                                                                                                                                                             │                    
       │   759 │   │   │   # load into object, no more substitute                                                                                                                                                                                                                         │                    
       │ ❱ 760 │   │   │   obj = JAML.load(tag_yml, substitute=False, runtime_args=runtime_args)                                                                                                                                                                                          │                    
       │   761 │   │   │   if not isinstance(obj, cls):                                                                                                                                                                                                                                   │                    
       │   762 │   │   │   │   raise BadConfigSource(                                                                                                                                                                                                                                     │                    
       │   763 │   │   │   │   │   f'Can not construct {cls} object from {source}. Source might be an                                                                                                                                                                                     │                    
       │       invalid configuration.'                                                                                                                                                                                                                                                    │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/jina/jaml/__init__.py:174 in load                                                                                                                                                                                              │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │   171 │   │   :return: the Python object                                                                                                                                                                                                                                         │                    
       │   172 │   │                                                                                                                                                                                                                                                                      │                    
       │   173 │   │   """                                                                                                                                                                                                                                                                │                    
       │ ❱ 174 │   │   r = yaml.load(stream, Loader=get_jina_loader_with_runtime(runtime_args))                                                                                                                                                                                           │                    
       │   175 │   │                                                                                                                                                                                                                                                                      │                    
       │   176 │   │   if substitute:                                                                                                                                                                                                                                                     │                    
       │   177 │   │   │   r = JAML.expand_dict(r, context)                                                                                                                                                                                                                               │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/yaml/__init__.py:81 in load                                                                                                                                                                                                    │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    78 │   """                                                                                                                                                                                                                                                                    │                    
       │    79 │   loader = Loader(stream)                                                                                                                                                                                                                                                │                    
       │    80 │   try:                                                                                                                                                                                                                                                                   │                    
       │ ❱  81 │   │   return loader.get_single_data()                                                                                                                                                                                                                                    │                    
       │    82 │   finally:                                                                                                                                                                                                                                                               │                    
       │    83 │   │   loader.dispose()                                                                                                                                                                                                                                                   │                    
       │    84                                                                                                                                                                                                                                                                            │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/yaml/constructor.py:51 in get_single_data                                                                                                                                                                                      │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    48 │   │   # Ensure that the stream contains a single document and construct it.                                                                                                                                                                                              │                    
       │    49 │   │   node = self.get_single_node()                                                                                                                                                                                                                                      │                    
       │    50 │   │   if node is not None:                                                                                                                                                                                                                                               │                    
       │ ❱  51 │   │   │   return self.construct_document(node)                                                                                                                                                                                                                           │                    
       │    52 │   │   return None                                                                                                                                                                                                                                                        │                    
       │    53 │                                                                                                                                                                                                                                                                          │                    
       │    54 │   def construct_document(self, node):                                                                                                                                                                                                                                    │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/yaml/constructor.py:55 in construct_document                                                                                                                                                                                   │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    52 │   │   return None                                                                                                                                                                                                                                                        │                    
       │    53 │                                                                                                                                                                                                                                                                          │                    
       │    54 │   def construct_document(self, node):                                                                                                                                                                                                                                    │                    
       │ ❱  55 │   │   data = self.construct_object(node)                                                                                                                                                                                                                                 │                    
       │    56 │   │   while self.state_generators:                                                                                                                                                                                                                                       │                    
       │    57 │   │   │   state_generators = self.state_generators                                                                                                                                                                                                                       │                    
       │    58 │   │   │   self.state_generators = []                                                                                                                                                                                                                                     │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/yaml/constructor.py:100 in construct_object                                                                                                                                                                                    │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    97 │   │   │   │   elif isinstance(node, MappingNode):                                                                                                                                                                                                                        │                    
       │    98 │   │   │   │   │   constructor = self.__class__.construct_mapping                                                                                                                                                                                                         │                    
       │    99 │   │   if tag_suffix is None:                                                                                                                                                                                                                                             │                    
       │ ❱ 100 │   │   │   data = constructor(self, node)                                                                                                                                                                                                                                 │                    
       │   101 │   │   else:                                                                                                                                                                                                                                                              │                    
       │   102 │   │   │   data = constructor(self, tag_suffix, node)                                                                                                                                                                                                                     │                    
       │   103 │   │   if isinstance(data, types.GeneratorType):                                                                                                                                                                                                                          │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/jina/jaml/__init__.py:582 in _from_yaml                                                                                                                                                                                        │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │   579 │   │   data = constructor.construct_mapping(node, deep=True)                                                                                                                                                                                                              │                    
       │   580 │   │   from jina.jaml.parsers import get_parser                                                                                                                                                                                                                           │                    
       │   581 │   │                                                                                                                                                                                                                                                                      │                    
       │ ❱ 582 │   │   return get_parser(cls, version=data.get('version', None)).parse(                                                                                                                                                                                                   │                    
       │   583 │   │   │   cls, data, runtime_args=constructor.runtime_args                                                                                                                                                                                                               │                    
       │   584 │   │   )                                                                                                                                                                                                                                                                  │                    
       │   585                                                                                                                                                                                                                                                                            │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/jina/jaml/parsers/executor/legacy.py:88 in parse                                                                                                                                                                               │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    85 │   │   │   │   runtime_args=runtime_args,                                                                                                                                                                                                                                 │                    
       │    86 │   │   │   )                                                                                                                                                                                                                                                              │                    
       │    87 │   │   else:                                                                                                                                                                                                                                                              │                    
       │ ❱  88 │   │   │   obj = cls(                                                                                                                                                                                                                                                     │                    
       │    89 │   │   │   │   **data.get('with', {}),                                                                                                                                                                                                                                    │                    
       │    90 │   │   │   │   metas=data.get('metas', {}),                                                                                                                                                                                                                               │                    
       │    91 │   │   │   │   requests=data.get('requests', {}),                                                                                                                                                                                                                         │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/jina/serve/executors/decorators.py:117 in arg_wrapper                                                                                                                                                                          │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │   114 │   │   │   │   │   file_lock = filelock.FileLock(lock_file, timeout=-1)                                                                                                                                                                                                   │                    
       │   115 │   │   │   │                                                                                                                                                                                                                                                              │                    
       │   116 │   │   │   │   with file_lock:                                                                                                                                                                                                                                            │                    
       │ ❱ 117 │   │   │   │   │   f = func(self, *args, **kwargs)                                                                                                                                                                                                                        │                    
       │   118 │   │   │   │   return f                                                                                                                                                                                                                                                   │                    
       │   119 │   │   │   else:                                                                                                                                                                                                                                                          │                    
       │   120 │   │   │   │   return func(self, *args, **kwargs)                                                                                                                                                                                                                         │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/jina/serve/executors/decorators.py:76 in arg_wrapper                                                                                                                                                                           │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    73 │   │   else:                                                                                                                                                                                                                                                              │                    
       │    74 │   │   │   self._init_kwargs_dict = tmp                                                                                                                                                                                                                                   │                    
       │    75 │   │   convert_tuple_to_list(self._init_kwargs_dict)                                                                                                                                                                                                                      │                    
       │ ❱  76 │   │   f = func(self, *args, **kwargs)                                                                                                                                                                                                                                    │                    
       │    77 │   │   return f                                                                                                                                                                                                                                                           │                    
       │    78 │                                                                                                                                                                                                                                                                          │                    
       │    79 │   return arg_wrapper                                                                                                                                                                                                                                                     │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /mnt/batch/tasks/shared/LS_root/mounts/clusters/dalle/code/Users/user/dalle/dalle-flow/executors/store/executor.py:9 in __init__                                                                                                                                        │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    6 │                                                                                                                                                                                                                                                                           │                    
       │    7 │   def __init__(self, store_path: str, **kwargs):                                                                                                                                                                                                                          │                    
       │    8 │   │   super().__init__(**kwargs)                                                                                                                                                                                                                                          │                    
       │ ❱  9 │   │   self.storage = DocumentArray(storage='sqlite', config={'connection': store_path,                                                                                                                                                                                    │                    
       │      'table_name': f'dallemega'})                                                                                                                                                                                                                                                │                    
       │   10 │   │   #self.storage = DocumentArray(config={'connection': store_path, 'table_name':                                                                                                                                                                                       │                    
       │      f'dallemega'})                                                                                                                                                                                                                                                              │                    
       │   11 │                                                                                                                                                                                                                                                                           │                    
       │   12 │   @requests(on='/upscale')                                                                                                                                                                                                                                                │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/docarray/array/base.py:12 in __init__                                                                                                                                                                                          │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    9 class BaseDocumentArray(MutableSequence[Document]):                                                                                                                                                                                                                         │                    
       │   10 │   def __init__(self, *args, storage: str = 'memory', **kwargs):                                                                                                                                                                                                           │                    
       │   11 │   │   super().__init__()                                                                                                                                                                                                                                                  │                    
       │ ❱ 12 │   │   self._init_storage(*args, **kwargs)                                                                                                                                                                                                                                 │                    
       │   13 │                                                                                                                                                                                                                                                                           │                    
       │   14 │   def __add__(self: 'T', other: Union['Document', Iterable['Document']]) -> 'T':                                                                                                                                                                                          │                    
       │   15 │   │   v = type(self)(self)                                                                                                                                                                                                                                                │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/docarray/array/storage/sqlite/backend.py:104 in _init_storage                                                                                                                                                                  │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │   101 │   │   )                                                                                                                                                                                                                                                                  │                    
       │   102 │   │   self._persist = bool(config.table_name)                                                                                                                                                                                                                            │                    
       │   103 │   │   config.table_name = self._table_name                                                                                                                                                                                                                               │                    
       │ ❱ 104 │   │   initialize_table(                                                                                                                                                                                                                                                  │                    
       │   105 │   │   │   self._table_name, self.__class__.__name__, self.schema_version, self._cursor                                                                                                                                                                                   │                    
       │   106 │   │   )                                                                                                                                                                                                                                                                  │                    
       │   107 │   │   self._connection.commit()                                                                                                                                                                                                                                          │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/docarray/array/storage/sqlite/helper.py:8 in initialize_table                                                                                                                                                                  │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │    5 │   table_name: str, container_type_name: str, schema_version: str, cur: sqlite3.Cursor                                                                                                                                                                                     │                    
       │    6 ) -> None:                                                                                                                                                                                                                                                                  │                    
       │    7 │   if not _is_metadata_table_initialized(cur):                                                                                                                                                                                                                             │                    
       │ ❱  8 │   │   _do_initialize_metadata_table(cur)                                                                                                                                                                                                                                  │                    
       │    9 │                                                                                                                                                                                                                                                                           │                    
       │   10 │   if not _is_table_initialized(table_name, container_type_name, schema_version, cur):                                                                                                                                                                                     │                    
       │   11 │   │   _do_create_table(table_name, cur)                                                                                                                                                                                                                                   │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │ /anaconda/envs/tunfas/lib/python3.8/site-packages/docarray/array/storage/sqlite/helper.py:26 in _do_initialize_metadata_table                                                                                                                                                    │                    
       │                                                                                                                                                                                                                                                                                  │                    
       │   23                                                                                                                                                                                                                                                                             │                    
       │   24                                                                                                                                                                                                                                                                             │                    
       │   25 def _do_initialize_metadata_table(cur: sqlite3.Cursor) -> None:                                                                                                                                                                                                             │                    
       │ ❱ 26 │   cur.execute(                                                                                                                                                                                                                                                            │                    
       │   27 │   │   '''                                                                                                                                                                                                                                                                 │                    
       │   28 │   │   CREATE TABLE metadata (                                                                                                                                                                                                                                             │                    
       │   29 │   │   │   table_name TEXT PRIMARY KEY,                                                                                                                                                                                                                                    │                    
       ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                    
       OperationalError: database is locked                                                                                                                                                                                                                                                                    
DEBUG  store/rep-0@18161 process terminated                                                                                                                                                                                                                                                                    
DEBUG  store/rep-0@18022 waiting for ready or shutdown signal from runtime                                                                                                                                                                                                                  [06/22/22 11:15:05]
DEBUG  store/rep-0@18022 shutdown is is already set. Runtime will end gracefully on its own                                                                                                                                                                                                                    
DEBUG  store/rep-0@18022 terminated                                                                                                                                                                                                                                                                            
DEBUG  store/rep-0@18022 joining the process                                                                                                                                                                                                                                                                   
DEBUG  store/rep-0@18022 successfully joined the process                                                                                                                                                                                                                                                       
ERROR  Flow@18022 Flow is aborted due to ['store'] can not be started.                                                                                                                                                                                                                      [06/22/22 11:15:05]
DEBUG  gateway/rep-0@18022 waiting for ready or shutdown signal from runtime                                                                                                                                                                                                                [06/22/22 11:15:05]
DEBUG  gateway/rep-0@18022 terminate                                                                                                                                                                                                                                                                           
DEBUG  gateway/rep-0@18022 terminating the runtime process                                                                                                                                                                                                                                                     
DEBUG  gateway/rep-0@18022 runtime process properly terminated                                                                                                                                                                                                                                                 
⠴ Waiting store ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 1/2 0:00:06DEBUG  gateway/rep-0@18162 process terminated                                                                                                                                                                                                                                               [06/22/22 11:15:06]
DEBUG  gateway/rep-0@18022 terminated                                                                                                                                                                                                                                                       [06/22/22 11:15:06]
DEBUG  gateway/rep-0@18022 joining the process                                                                                                                                                                                                                                                                 
DEBUG  gateway/rep-0@18022 successfully joined the process                                                                                                                                                                                                                                                     
Traceback (most recent call last):
  File "/anaconda/envs/tunfas/bin/jina", line 8, in <module>
    sys.exit(main())
  File "/anaconda/envs/tunfas/lib/python3.8/site-packages/jina_cli/__init__.py", line 143, in main
    getattr(api, args.cli.replace('-', '_'))(args)
  File "/anaconda/envs/tunfas/lib/python3.8/site-packages/jina_cli/api.py", line 162, in flow
    with f:
  File "/anaconda/envs/tunfas/lib/python3.8/site-packages/jina/orchestrate/flow/base.py", line 1137, in __enter__
    return self.start()
  File "/anaconda/envs/tunfas/lib/python3.8/site-packages/jina/orchestrate/flow/builder.py", line 33, in arg_wrapper
    return func(self, *args, **kwargs)
  File "/anaconda/envs/tunfas/lib/python3.8/site-packages/jina/orchestrate/flow/base.py", line 1193, in start
    self._wait_until_all_ready()
  File "/anaconda/envs/tunfas/lib/python3.8/site-packages/jina/orchestrate/flow/base.py", line 1291, in _wait_until_all_ready
    raise RuntimeFailToStart
jina.excepts.RuntimeFailToStart
```

**Comment by JoanFM** [comment]
hey @mistamun,

have u tried with a different store path to see if it works?

**Comment by mistamun** [comment]
`/tmp/dalle-flow' works. Very odd because I could see dalle_flow.db get created with correct permissions in the local folder.

**Comment by delgermurun** [comment]
Using sqlite no longer, so this should be resolved.
